### PR TITLE
Fix YAML linter errors

### PR DESCRIPTION
**Pull request by rdavid**

### CODE REVIEW

**Review by sebrandon1 — APPROVED** [review]

**Review by greyerof — COMMENTED** [review]
Where are these yaml linting issues happening?

**Comment by rdavid** [comment]
@greyerof I noticed the errors in my editor (vim) by accident, yamllint is ran on every opened YAML file.

**Comment by rdavid** [comment]
You can see the errors `yamllint .github/workflows/tnf-image.yaml`.

**Comment by rdavid** [comment]
The action uses the same `yamllint`, is should be reconfigured to be more restrictive in separate PR.

**Comment by rdavid** [comment]
You can see 193 warnings:
 https://github.com/test-network-function/cnf-certification-test/actions/runs/3884669770/jobs/6627542100
 
The PR fixes warnings, not errors.

**Comment by rdavid** [comment]
There is the config:
```
  yamllint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            extends: default
            rules:
              line-length:
                level: warning
              trailing-spaces:
                level: warning
              brackets:
                level: warning
              empty-lines:
                level: warning
```
It should be more restrictive, otherwise what is a point for linter.

**Comment by greyerof** [comment]
Usually, linting is a debatable/subjective matter: that's why those tools allow you to change levels and customize some of the rules. E.g. the default max length for lines is 80, but it can be manually configured with `yamllint` to any other value. Should we use that value or should we use a more relaxed value (120)?

image

I don't mind setting it in a bit more restrictive mode, although I don't believe it will pay off for most of those warnings, honestly.

**Comment by rdavid** [comment]
120 is OK. Linters are good tools, Go has built in.

**Review by greyerof — APPROVED** [review]

**Pull request merged**
