### PR TITLE
Propagate errors from preflight in the claim file 

### PR DESCRIPTION
**Pull request by edcdavid**
Propagates errors from preflight in the claim file  even if preflight fails to run due to connectivity issues, missing docker config, etc...
~~Also contains temporary workaround for leftover ginkgo code in lifecycle, see https://github.com/test-network-function/cnf-certification-test/pull/1679~~

### CODE REVIEW

**Review by Apetree100122 — APPROVED** [review]

**Comment by ramperher** [comment]
I just wanted to check that DCI jobs are now correctly scheduled even if they come from ginkgo_removal branch, since we verified it's stable from DCI side.

**Comment by ramperher** [comment]
DCI job is failing when trying to build the tnf image locally: https://www.distributed-ci.io/jobs/1cd9f0ef-ad33-4eef-80c2-4196b386ff27/jobStates, could be a transient issue. If you need to merge this, it's not a problem, but it's preferrable to have this working if possible.

**Comment by edcdavid** [comment]
> DCI job is failing when trying to build the tnf image locally: https://www.distributed-ci.io/jobs/1cd9f0ef-ad33-4eef-80c2-4196b386ff27/jobStates, could be a transient issue. If you need to merge this, it's not a problem, but it's preferrable to have this working if possible.
This might be due to this PR using depends-on github action. Once the dependency is merged it should be able to pass DCI

**Review by sebrandon1 — APPROVED** [review]

**Review by greyerof — APPROVED** [review]

**Pull request merged**
