### PR TITLE
Avoid crashing when discoverying CR scales.

### PR DESCRIPTION
**Pull request by greyerof**
The previous code was crashing because it was trying to get the Scale object of each CR found, without considering whether the CRD spec was configured to have a scale subresource. In those cases, using the Get() of the dynamic client to retrieve the Scale corresponding to those CRs was returning a NotFound err.

The test case "lifecycle-crd-scaling" has also been fixed to skip when the list of scaleCrUnderTest is empty.
```
- testhelper.SkipIfEmptyAny(ginkgo.Skip, env.Crds)
+ testhelper.SkipIfEmptyAny(ginkgo.Skip, env.ScaleCrUndetTest)
```
Without this change, the TC was marked as "passed" even when no CRs were found in the target namespaces of the cluster CRDs matching the configured suffixes.

More changes:
- The scale objects won't be searched for cluster-wide CRDs.
- I did some refactoring to the functions related to searching the scales and creating the custom ScaleObject lists.
- File names were also changed to pure snake case.

### CODE REVIEW

**Comment by ramperher** [comment]
@greyerof , just a question. With this change, now `lifecycle-crd-scaling` test is skipped in our deployments: https://www.distributed-ci.io/jobs/c0e037e1-3562-4216-bf51-adf24a156422/tests, and it was executed correctly before, e.g.: https://www.distributed-ci.io/jobs/0e2fd4e7-690c-442a-ab14-86074a421576/tests/86f152ad-6f60-4dfe-b647-bc678be09edd. Now the test result says:

```
> Enter [BeforeEach] lifecycle - /usr/tnf/tnf-src/cnf-certification-test/lifecycle/suite.go:55 @ 04/28/23 07:08:17.012
< Exit [BeforeEach] lifecycle - /usr/tnf/tnf-src/cnf-certification-test/lifecycle/suite.go:55 @ 04/28/23 07:08:17.012 (0s)
> Enter [It] lifecycle-crd-scaling - /usr/tnf/tnf-src/cnf-certification-test/lifecycle/suite.go:66 @ 04/28/23 07:08:17.012
[SKIPPED] Test skipped because there are no []provider.ScaleObject to test, please check under test labels
In [It] at: /usr/tnf/tnf-src/pkg/testhelper/testhelper.go:130 @ 04/28/23 07:08:17.012
< Exit [It] lifecycle-crd-scaling - /usr/tnf/tnf-src/cnf-certification-test/lifecycle/suite.go:66 @ 04/28/23 07:08:17.012 (0s)
> Enter [ReportAfterEach] lifecycle - /usr/tnf/tnf-src/cnf-certification-test/lifecycle/suite.go:58 @ 04/28/23 07:08:17.012
< Exit [ReportAfterEach] lifecycle - /usr/tnf/tnf-src/cnf-certification-test/lifecycle/suite.go:58 @ 04/28/23 07:08:17.012 (0s)
```

Is this a fix (so that before it was passing and it shouldn't) or is this something to review?

**Comment by ramperher** [comment]
> @greyerof , just a question. With this change, now `lifecycle-crd-scaling` test is skipped in our deployments: https://www.distributed-ci.io/jobs/c0e037e1-3562-4216-bf51-adf24a156422/tests, and it was executed correctly before, e.g.: https://www.distributed-ci.io/jobs/0e2fd4e7-690c-442a-ab14-86074a421576/tests/86f152ad-6f60-4dfe-b647-bc678be09edd. Now the test result says:
> 
> ```
> > Enter [BeforeEach] lifecycle - /usr/tnf/tnf-src/cnf-certification-test/lifecycle/suite.go:55 @ 04/28/23 07:08:17.012
> < Exit [BeforeEach] lifecycle - /usr/tnf/tnf-src/cnf-certification-test/lifecycle/suite.go:55 @ 04/28/23 07:08:17.012 (0s)
> > Enter [It] lifecycle-crd-scaling - /usr/tnf/tnf-src/cnf-certification-test/lifecycle/suite.go:66 @ 04/28/23 07:08:17.012
> [SKIPPED] Test skipped because there are no []provider.ScaleObject to test, please check under test labels
> In [It] at: /usr/tnf/tnf-src/pkg/testhelper/testhelper.go:130 @ 04/28/23 07:08:17.012
> < Exit [It] lifecycle-crd-scaling - /usr/tnf/tnf-src/cnf-certification-test/lifecycle/suite.go:66 @ 04/28/23 07:08:17.012 (0s)
> > Enter [ReportAfterEach] lifecycle - /usr/tnf/tnf-src/cnf-certification-test/lifecycle/suite.go:58 @ 04/28/23 07:08:17.012
> < Exit [ReportAfterEach] lifecycle - /usr/tnf/tnf-src/cnf-certification-test/lifecycle/suite.go:58 @ 04/28/23 07:08:17.012 (0s)
> ```
> 
> Is this a fix (so that before it was passing and it shouldn't) or is this something to review?

Reviewed with Gonzalo, it's the expected output, so nothing more to add here!

**Review by edcdavid — APPROVED** [review]

**Comment by ramperher** [comment]
DCI job is not being launched because of rebasing issue: `ERROR unable to rebase PR 1056 from test-network-function/cnf-certification-test branch main branch`, but as I said, the code was tested correctly before, so from my side it's fine to merge.

**Comment by greyerof** [comment]
After talking to Ramon about the DCI issue, looks like that DCI job doesn't like the "merge commits" I used to update the PR branch with main. I'll merge this PR as he already tested it to work fine before the merge commits and he'll investigate the possiblity of a workaround for this in the DCI scripts.

**Pull request merged**
