### PR TITLE
Update preflight to v1.9.1

### PR DESCRIPTION
**Pull request by sebrandon1**
build-depends: https://github.com/dci-labs/dallas-pipelines/pull/1042

https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.9.1

### CODE REVIEW

**Review by rdavid — APPROVED** [review]

**Comment by manurodriguez** [comment]
@sebrandon1 let me re-test this with https://github.com/dci-labs/dallas-pipelines/pull/1042 to ignore the `preflight-RequiredAnnotations` test

**Comment by manurodriguez** [comment]
With https://github.com/dci-labs/dallas-pipelines/pull/1042 the job passed, however there I'm ignoring the `preflight-RequiredAnnotations` tests. And in a related topic, I see that @tkrishtop moved also to preflight 1.9.0 in our ansible collection:  https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/183 to force the RequiredAnnotations check, so I'm not sure if ignoring the test in my PR is a good idea, maybe we need to do something else in our test workload to add the annotations. Please let me sync with Tatiana and the team to understand this.

**Comment by sebrandon1** [comment]
@manurodriguez I had to update this PR to v1.9.1 since they released a new one slightly after I put up my original PR:
https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.9.1

**Comment by manurodriguez** [comment]
> @manurodriguez I had to update this PR to v1.9.1 since they released a new one slightly after I put up my original PR: https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.9.1

@sebrandon1 sounds good, I'm about to send a change in our agent to add the missing annotations in the operator we use for TNF validation and make the preflight-RequiredAnnotations tests pass, otherwise the job will keep failing.

**Comment by manurodriguez** [comment]
@sebrandon1 Could you please add a `build-depends: 31001` in the first comment of your PR and re-run the job? I tested that PR independently to set the operator [feature annotations](https://docs.openshift.com/container-platform/4.15/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-annotations-infra_osdk-generating-csvs) and looks good, so let's see it goes when you run the preflight tests with TNF.

**Comment by manurodriguez** [comment]
@sebrandon1 let's go back to include `build-depends: https://github.com/dci-labs/dallas-pipelines/pull/1042` in this change to unblock you, then we'll look more carefully how to test the operator annotations in our sample tests

**Comment by sebrandon1** [comment]
@manurodriguez Okay updated.

**Comment by manurodriguez** [comment]
Thanks, I'm relaunching the test:

/dci-rerun

**Comment by manurodriguez** [comment]
well, I can't re-run the test, I got: `manurodriguez unauthorized to call /dci-rerun` @sebrandon1 please just relaunch the test from your side

**Pull request merged**
