### PR TITLE
Switch clientsholder to user constructor style

### PR DESCRIPTION
**Pull request by sebrandon1**
Further compartmentalize the clientsholder `Context` struct by using a more constructor-esque style with appropriate Getter functions.

Created a new `NewContext` func to help build clientsholder.Context objects.

### CODE REVIEW

**Review by greyerof — APPROVED** [review]

**Comment by ramperher** [comment]
check workload tnf-test-cnf-green tnf-test-cnf-green:ansible_extravars=provisioner_user:""

**Comment by ramperher** [comment]
> check workload tnf-test-cnf-green tnf-test-cnf-green:ansible_extravars=provisioner_user:""

This is the way of launching DCI tests manually for your PRs, by the way (but I am looking for a way of doing it shorter)

**Comment by ramperher** [comment]
check workload tnf-test-cnf-green

**Comment by ramperher** [comment]
> check workload tnf-test-cnf-green

This is the way of launching DCI tests manually for your PRs, by the way (but I am looking for a way of doing it shorter)

**Pull request merged**
