### PR TITLE
Fix for backward compatible label support

### PR DESCRIPTION
**Pull request by edcdavid**
The deprecated label used for operator will be match with any value. The previous PR introducing new labelling procedure broke this wildcard mechanism. This PR adds it back.
fix regression with last PR introducing new labels:
- using a list of strings instead of Map to store labels
- use the correct label for statefulset and deployments under test

### CODE REVIEW

**Comment by ramperher** [comment]
Don't know if further integrations to fix backward compatibility with label support will be included here or in other patches, but just to say that there are some other issues related to the transition to the new label support that are documented in Jira

**Review by rdavid — APPROVED** [review]

**Review by sebrandon1 — APPROVED** [review]

**Comment by edcdavid** [comment]
> 

@ramperher thanks for the previous testing. Could you give it another try with this PR?

**Comment by ramperher** [comment]
For the moment, the legacy configuration is [working fine](https://www.distributed-ci.io/jobs/77405057-609e-4314-b3f9-ccf88e89f83a/jobStates), let me try with the new one

**Review by ramperher — CHANGES_REQUESTED** [review]
It's still not working when having the same label key, see this job: https://www.distributed-ci.io/jobs/8d27ad57-d827-4aef-b41e-a7d986117e2d/files

dci-tnf-execution.log
```
[36mINFO   [0m[Apr 28 08:01:31.113][utils.go: 51] Loading config from file: /usr/tnf/config/tnf_config.yml 
[31mFATAL  [0m[Apr 28 08:01:31.114][provider.go: 202] Cannot load configuration file: yaml: unmarshal errors:
  line 8: mapping key "environment" already defined at line 7
  line 12: cannot unmarshal !!map into []string 
```

tnf_config.yml
```
targetNameSpaces:
  - name: test-cnf
  - name: production-cnf

podsUnderTestLabels:
  environment: test
  environment: production

operatorsUnderTestLabels:
  test-network-function.com/operator: target

...
```

The other issues (operator and lifecycle tests) seem to be fixed, at least testing with the legacy config. But the problem with the labels is still present.

**Comment by ramperher** [comment]
> * dci-check-change  : FAILURE tested on libvirt:virt
> * libvirt -> success: https://www.distributed-ci.io/jobs/7a2e7cdf-8e58-4da1-b134-828d5e82e67c/jobStates
> * tnf_test_example -> failure: https://www.distributed-ci.io/jobs/5e1cc3de-1760-40c5-b7da-ac47778b9f4d/jobStates

And in this job, even using different labels:

tnf_config.yml
```
podsUnderTestLabels:
  environment1: test
  environment2: production
```

It's still failing due to a different reason:

```
[36mINFO   [0m[Apr 28 08:40:33.229][utils.go: 51] Loading config from file: /usr/tnf/config/tnf_config.yml 
[31mFATAL  [0m[Apr 28 08:40:33.229][provider.go: 202] Cannot load configuration file: yaml: unmarshal errors:
  line 7: cannot unmarshal !!map into []string
  line 12: cannot unmarshal !!map into []string 
```

> It's still not working when having the same label key, see this job: https://www.distributed-ci.io/jobs/8d27ad57-d827-4aef-b41e-a7d986117e2d/files
> 
> dci-tnf-execution.log
> 
> ```
> �[36mINFO   �[0m[Apr 28 08:01:31.113][utils.go: 51] Loading config from file: /usr/tnf/config/tnf_config.yml 
> �[31mFATAL  �[0m[Apr 28 08:01:31.114][provider.go: 202] Cannot load configuration file: yaml: unmarshal errors:
>   line 8: mapping key "environment" already defined at line 7
>   line 12: cannot unmarshal !!map into []string 
> ```
> 
> tnf_config.yml
> 
> ```
> targetNameSpaces:
>   - name: test-cnf
>   - name: production-cnf
> 
> podsUnderTestLabels:
>   environment: test
>   environment: production
> 
> operatorsUnderTestLabels:
>   test-network-function.com/operator: target
> 
> ...
> ```
> 
> The other issues (operator and lifecycle tests) seem to be fixed, at least testing with the legacy config. But the problem with the labels is still present.

it was my fault, I wasn't included correctly the data in tnf_config.yml (as a list and each element between quotes). Now I've tested with that and I can confirm the results are fine, so I'm fine to merge this!

**Review by ramperher — APPROVED** [review]

**Comment by ramperher** [comment]
Sorry for the amount of tests, validating different scenarios, but everything is fine, this can be merged.

**Comment by edcdavid** [comment]
> Sorry for the amount of tests, validating different scenarios, but everything is fine, this can be merged.

Great, thanks for the thorough the testing !

**Pull request merged**
