### PR TITLE
Batch operators test catalog source automation

### PR DESCRIPTION
**Pull request by shirmoran**
Instead of getting as an input a catalog name, the script will get a catalog index and will create a "CatalogSource" resource based on it.  At the end of the run the "CatalogSource" will be deleted.

* In addition the "status" variable was removed - the exit code is checked after every command and an error will appear if necessary.

### CODE REVIEW

**Comment by tonyskapunk** [comment]
check workload

**Comment by tonyskapunk** [comment]
check workload tnf-test-cnf-green

**Comment by jmontesi** [comment]
In my view, this bash script is reaching the point where I would consider translating it to another language, such as Python o even Go. What do you think?

**Review by rdavid — APPROVED** [review]

**Review by sebrandon1 — APPROVED** [review]

**Review by edcdavid — APPROVED** [review]
Great work Thx!

**Pull request merged**
